src/WebApplication6/Controllers/linksController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication6;
using System.Collections.Generic;
using System;
using System.IO;
using System.Diagnostics;
using System.Text.RegularExpressions;
using System.Data;
using System.Data.SqlClient;

using MoreLinq;


namespace WebApplication6.Controllers
{
    public class linksController : Controller
    {
        private testing2Context _context;

        public linksController(testing2Context context)
        {
            _context = context;    
        }

        [ActionName("Canvas")]
        public IActionResult Canvas(int param1, string param2)
        {
            return View(new CanvasInitialViewModel() { initial_id = param1, initial_type = param2 });
        }

        [HttpPost, ActionName("GetModel")]
        public CanvasViewModel GetModel([FromBody] CanvasRecieveParams input)
        {
            var viewmodel = new CanvasViewModel();


            var maintable = new tables();
            var link = new links();
            var field = new fields();
            var forwardtables2 = new List<tables>();
            var backtables2 = new List<tables>();
            var forwardlinks = new List<links>();
            var backlinks = new List<links>();
            var linkforwardtable = new tables();

            var forwardtables1test = new List<links>();
            var forwardlinkstest = new List<links>();

            var include_interfaces = new List<int>();
            var all_interfaces = new List<int>();
            var all_interfaces_names = new List<string>();

            var id_ = input.new_id;

            int tbl = 0;

            var intfnames = _context.interfaces.Select(intf => new { intf.interface_id, intf.interface_name }).ToList();

            viewmodel.links = new List<CVMLink>();

            if (input.new_type == "link")
            {



                maintable = _context.links.Include(l => l.source_field).ThenInclude(f => f.table).ThenInclude(t => t.fields).ThenInclude(f => f.entity).Single(l => l.link_id == id_).source_field.table;

                link = _context.links.Include(l => l.source_field).ThenInclude(f => f.table).Include(l => l.destination_field).ThenInclude(f => f.table).Include(l => l._interface).Single(m => m.link_id == id_);

                include_interfaces.Add(link.interface_id ?? 0);

                field = null;

                linkforwardtable = _context.links.Include(l => l.destination_field).ThenInclude(f => f.table).ThenInclude(t => t.fields).ThenInclude(t2 => t2.entity).Single(l => l.link_id == id_).destination_field.table;

                var forwardtablescontext = _context.links.Include(l => l.source_field).ThenInclude(f => f.table).ThenInclude(t => t.fields).ThenInclude(f => f.linksNavigation).ThenInclude(l2 => l2.destination_field).ThenInclude(f2 => f2.table).ThenInclude(t2 => t2.fields).ThenInclude(t2 => t2.entity).Single(l => l.link_id == id_);

                if (forwardtablescontext?.source_field != null)
                {


                    var forwardtables1 = forwardtablescontext.source_field.table.fields.ToList();

                    forwardtables1test = forwardtables1.SelectMany(f => f.linksNavigation).ToList();

                    forwardtables2 = forwardtables1.SelectMany(f => f.linksNavigation).Where(l => l.link_id != id_ && include_interfaces.Contains(l.interface_id ?? 0)).Select(l => l.destination_field.table).ToList();

                    forwardlinks = forwardtables1.SelectMany(f => f.linksNavigation).Where(l => l?.source_field != null && l?.destination_field != null).ToList();

                }


                var backtablescontext = _context.links.Include(l => l.source_field).ThenInclude(f => f.table).ThenInclude(t => t.fields).ThenInclude(f => f.links).ThenInclude(l2 => l2.source_field).ThenInclude(f2 => f2.table).ThenInclude(t2 => t2.fields).ThenInclude(t2 => t2.entity).Single(l => l.link_id == id_);


                if (backtablescontext?.source_field != null)
                {
                    var backtables1 = backtablescontext.source_field.table.fields.ToList();

                    backtables2 = backtables1.SelectMany(f => f.links).Where(l => l.link_id != id_ && include_interfaces.Contains(l.interface_id ?? 0)).Select(l => l.source_field.table).ToList();



                    backlinks = backtables1.SelectMany(f => f.links).Where(l => l?.source_field != null && l?.destination_field != null).ToList();
                }

                all_interfaces = forwardlinks.Select(f => f.interface_id ?? 0).Union(backlinks.Select(f => f.interface_id ?? 0)).OrderBy(intf => intf).ToList();

                all_interfaces.Add(link.interface_id ?? 0);

                all_interfaces_names = all_interfaces.Select(intf => intfnames.Single(names => names.interface_id == intf).interface_name).ToList();



            }
            else
            {
                include_interfaces = input.including_interface_ids;

                maintable = _context.fields.Include(f => f.table).ThenInclude(t => t.fields).Single(f => f.field_id == id_).table;

                link = null;

                field = _context.fields.Single(f => f.field_id == input.new_id);

                linkforwardtable = null;

                var forwardtablescontext = _context.fields

                    .Include(f3 => f3.table).ThenInclude(t4 => t4.fields).ThenInclude(f2x => f2x.linksNavigation).ThenInclude(l2 => l2.destination_field).ThenInclude(f2 => f2.table).ThenInclude(t2 => t2.fields).ThenInclude(f5 => f5.entity).Single(f => f.field_id == id_);

                var forwardtables1 = forwardtablescontext.table.fields.ToList();

                forwardtables2 = forwardtables1.SelectMany(f => f.linksNavigation).Where(l => l.is_future == !input.is_current && include_interfaces.Contains(l.interface_id ?? 0)).Select(l => l?.destination_field?.table).Where(t => t != null).ToList();

                var backtablescontext = _context.fields.Include(f => f.table).ThenInclude(t => t.fields).ThenInclude(f => f.links).ThenInclude(l2 => l2.source_field).ThenInclude(f2 => f2.table).ThenInclude(t2 => t2.fields).ThenInclude(t2 => t2.entity).Single(f => f.field_id == id_);

                var backtables1 = backtablescontext.table.fields.ToList();

                backtables2 = backtables1.SelectMany(f => f.links).Where(l => l.is_future == !input.is_current && include_interfaces.Contains(l.interface_id ?? 0)).Select(l => l?.source_field?.table).Where(t => t != null).ToList();

                forwardlinks = forwardtables1.SelectMany(f => f.linksNavigation).Where(l => l?.source_field != null && l?.destination_field != null && l.is_future == !input.is_current).ToList();

                forwardlinkstest = forwardtables1.SelectMany(f => f.linksNavigation).ToList();

                backlinks = backtables1.SelectMany(f => f.links).Where(l => l?.source_field != null && l?.destination_field != null && l.is_future == !input.is_current).ToList();


                all_interfaces = forwardlinks.Select(f => f.interface_id ?? 0).Union(backlinks.Select(f => f.interface_id ?? 0)).Distinct().OrderBy(intf => intf).ToList();

                all_interfaces_names = all_interfaces.Select(intf => intfnames.Single(names => names.interface_id == intf).interface_name).ToList();

            }

            var start_x = 1750;
            var start_y = 1500;

            var validfields1 = _context.links.Select(l => l.source_field_id).ToList();
            var validfields2 = _context.links.Select(l => l.destination_field_id).ToList();
            var validfields = validfields1.Union(validfields2);

            var test = maintable.fields.Where(f => validfields.Contains(f.field_id));

            viewmodel.maintable = new CVMTable() { table_id = maintable.table_id, x = input.original_type == "new" ? start_x : input.new_x, y = input.original_type == "new" ? start_y : input.new_y, table_name = maintable.table_name, fields = maintable.fields.Where(f => validfields.Contains(f.field_id)).Select(f => GetField(f)).OrderBy(f => f.column_order).ThenBy(f => f.field_name).ToList() };
            if (link != null) { viewmodel.link = new CVMLink() { link_id = link.link_id, x1 = 0, x2 = 0, y1 = 0, y2 = 0, interface_id = link?.interface_id ?? -1, interface_name = intfnames.Single(names => names.interface_id == link.interface_id).interface_name, source_field = link?.source_field?.table.table_name + "." + link?.source_field?.field_name + " " + link?.source_field?.field_type + " " + ((link?.source_field?.field_length ?? 0) == 0 ? "" : "(" + link?.source_field?.field_length + ")"), dest_field = link?.destination_field?.table.table_name + "." + link?.destination_field?.field_name + " " + link?.destination_field?.field_type + " " + ((link?.destination_field?.field_length ?? 0) == 0 ? "" : "(" + link?.destination_field?.field_length + ")"), source_field_id = link.source_field_id ?? -1, dest_field_id = link.destination_field_id ?? -1 }; }
            if (field != null) { viewmodel.field = new CVMField() { field_id = field.field_id, field_name = field.field_name }; }

            var ftables = forwardtables2
                .DistinctBy(t => t.table_id)
                .Select(t => new CVMTable() { table_id = t.table_id, x = input.original_type == "new" ? start_x + 250 : input.new_x + 250, y = 0, table_name = t.table_name, isforward = true, fields = t.fields.Where(f => validfields.Contains(f.field_id)).Select(f => GetField(f)).OrderBy(f => f.column_order).ThenBy(f => f.field_name).ToList() }).ToList();
            var btables = backtables2
                .DistinctBy(t => t.table_id)

src/WebApplication6/Views/links/Delete.cshtml
@model WebApplication6.links

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>links</h4>
    <hr />
    <dl class="dl-horizontal">
        
        <dt>
            @Html.DisplayNameFor(model => model.is_future)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.is_future)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.link_column_num)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.link_column_num)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.transformation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.transformation)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.business_logic)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.business_logic)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.where_conditions)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.where_conditions)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/WebApplication6/Views/links/Details.cshtml
@model WebApplication6.links

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>links</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model._interface.interface_name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model._interface.interface_name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.is_future)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.is_future)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.batch)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.batch)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.link_column_num)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.link_column_num)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.source_field.table.table_name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.source_field.table.table_name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.source_field.field_name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.source_field.field_name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.destination_field.table.table_name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.destination_field.table.table_name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.destination_field.field_name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model._interface.interface_name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.transformation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.transformation)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.business_logic)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.business_logic)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.where_conditions)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.where_conditions)
        </dd>
    </dl>
</div>
<p>
    <a asp-action="Edit" asp-route-project="1" asp-route-id="@Model.link_id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</p>

src/WebApplication6/Views/links/Edit.cshtml
@model WebApplication6.links

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>links</h4>
        <hr />
        
        <input type="hidden" asp-for="link_id" />
        <input type="hidden" asp-for="interface_id" />
        <input type="hidden" asp-for="batch" />
        <input type="hidden" asp-for="source_field_id" />
        <input type="hidden" asp-for="destination_field_id" />
        <input type="hidden" asp-for="is_future" />
        <div class="form-group">
            <label asp-for="transformation" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="transformation" class="form-control" readonly="readonly" />
                <span asp-validation-for="transformation" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="business_logic" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="business_logic" class="form-control" />
                <span asp-validation-for="business_logic" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="where_conditions" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="where_conditions" class="form-control" readonly="readonly" />
                <span asp-validation-for="where_conditions" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/WebApplication6/Views/links/ExceptionReport.cshtml
@model IEnumerable<WebApplication6.ExceptionReportViewModel>

@{
    ViewData["Title"] = "Index";
}

<h2>Exception Report</h2>

<br />

<table class="table" align="left">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.interface_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.exception)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.is_future)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.source_field)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dest_field)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.transformation)
        </th>
        <th>Options</th>
</tr>
    
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.interface_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.exception)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.is_future)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.source_field)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dest_field)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.transformation)
        </td>
        <td>
            <a asp-action="Canvas" asp-route-param1="@item.link_id" asp-route-param2="link">View</a> |
            <a asp-action="Edit" asp-route-project="1" asp-route-id="@item.link_id">Edit</a> |     
        </td>
    </tr>
}
</table>

src/WebApplication6/Views/links/Index.cshtml
@model IEnumerable<WebApplication6.links>

@{
    ViewData["Title"] = "Index";
}

<h2>Links</h2>

<br />

<form asp-action="Index">
    <div class="form-inline">
        <div class="form-group">
            <div class="col-md-10">
                <input class="form-control" name="name" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Search" class="btn btn-default" />
            </div>
            <input type="hidden" value="@ViewData["source_id"]" name="sourceid" />
        </div>
    </div>
</form>

<br />

<table class="table" align="left">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.is_future)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.batch)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.link_column_num)
        </th>
        <th>
            Source Table
        </th>
        <th>
            Source Field
        </th>
        <th>
            Destination Table
        </th>
        <th>
            Destination Field
        </th>
        <th></th>
    </tr>
    
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.is_future)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.batch)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.link_column_num)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.source_field.table.table_name)
        </td>
        <td>           
            @Html.DisplayFor(modelItem => item.source_field.field_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.destination_field.table.table_name)         
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.destination_field.field_name)
        </td>
        <td>
            <a asp-controller="Links" asp-action="Canvas" asp-route-param1="@item.link_id" asp-route-param2="link">View</a>
            <a asp-action="Details" asp-route-project="1" asp-route-id="@item.link_id">Details</a> |
            <a asp-action="Edit" asp-route-project="1" asp-route-id="@item.link_id">Edit</a> |
            <a asp-action="Delete" asp-route-project="1" asp-route-id="@item.link_id">Delete</a>            
        </td>
    </tr>
}
</table>

@if ((int)ViewData["source_id"] > 0)
{
    <a asp-controller="interfaces" asp-action="Index" asp-route-project="1" asp-route-id="@ViewData["source_id"]">Back to Interfaces</a>
}

src/WebApplication6/Views/links/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Interface Catalogue</title>

        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-controller="interfaces" asp-action="Index" class="navbar-brand">Interface Catalogue</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="interfaces" asp-action="Index">Interfaces</a></li>
                        <li><a asp-controller="systems" asp-action="Index">Systems</a></li>
                        <li><a asp-controller="tables" asp-action="Index">Tables</a></li>
                        <li><a asp-controller="entities" asp-action="Index">Entities</a></li>
                        <li><a asp-controller="links" asp-action="ExceptionReport">Exception Report</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container-fluid body-content">
            @RenderBody()
            <hr />
            <footer>
            </footer>
        </div>

        <environment names="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment names="Staging,Production">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("scripts", required: false)
    </body>
</html>